create extension if not exists pgcrypto;
create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade);
create table if not exists public.chats (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, title text not null default 'Moj pogovor', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.messages (id bigint generated by default as identity primary key, chat_id uuid not null references public.chats(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check (role in ('user','assistant')), content text not null check (char_length(content) <= 5000), created_at timestamptz not null default now());
create table if not exists public.ideas (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null, nickname text not null check (char_length(nickname) between 1 and 30), idea text not null check (char_length(idea) between 1 and 1000), created_at timestamptz not null default now());
alter table public.admin_users enable row level security; alter table public.chats enable row level security; alter table public.messages enable row level security; alter table public.ideas enable row level security;
create or replace function public.is_admin() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()); $$;

drop policy if exists "users read own chats" on public.chats;
drop policy if exists "users create own chats" on public.chats;
drop policy if exists "users update own chats" on public.chats;
drop policy if exists "users read own messages" on public.messages;
drop policy if exists "users create own messages" on public.messages;
drop policy if exists "users delete own messages" on public.messages;
drop policy if exists "users submit ideas" on public.ideas;
drop policy if exists "admins read ideas" on public.ideas;
drop policy if exists "admins delete ideas" on public.ideas;

create policy "users read own chats" on public.chats for select to authenticated using (user_id=auth.uid());
create policy "users create own chats" on public.chats for insert to authenticated with check (user_id=auth.uid());
create policy "users update own chats" on public.chats for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "users read own messages" on public.messages for select to authenticated using (user_id=auth.uid());
create policy "users create own messages" on public.messages for insert to authenticated with check (user_id=auth.uid());
create policy "users delete own messages" on public.messages for delete to authenticated using (user_id=auth.uid());
create policy "users submit ideas" on public.ideas for insert to authenticated with check (user_id=auth.uid());
create policy "admins read ideas" on public.ideas for select to authenticated using (public.is_admin());
create policy "admins delete ideas" on public.ideas for delete to authenticated using (public.is_admin());
-- After creating your own account, run: insert into public.admin_users(user_id) values ('YOUR_AUTH_USER_UUID');
